//! `rusty-idd render` — generate the minimal vendor adapter for each agent
//! surface from one engine-owned template, and `--check` them as a fail-closed
//! drift gate (ADR-0010, ADR-0015).
//!
//! Vendor directories (`.claude`, `.codex`, `.agents`, `.devin`) are thin
//! adapters: the workflow lives in the Rusty IDD engine, the adapter only points
//! agents at `rusty-idd next`. `render` writes the adapter; `render --check`
//! fails when an on-disk adapter is missing or hand-edited away from the engine
//! output, so vendor dirs cannot silently grow back into prose harnesses.

use std::path::PathBuf;

use clap::Args;

/// Known vendor surfaces: `(name, directory)`. Adoption of a new surface is a
/// deliberate, reviewed code change here. Shared with `commands::deploy`
/// (`pub(crate)`) so fleet deploy targets exactly the same vendor set as render.
pub(crate) const VENDORS: &[(&str, &str)] = &[
    ("claude", ".claude"),
    ("codex", ".codex"),
    ("agents", ".agents"),
    ("devin", ".devin"),
];

pub(crate) const ADAPTER_FILE: &str = "rusty-idd-adapter.md";

/// Args for `rusty-idd render`.
#[derive(Args)]
pub struct RenderArgs {
    /// Render a single vendor by name (claude|codex|agents|devin).
    #[arg(long, conflicts_with = "all")]
    vendor: Option<String>,
    /// Render every known vendor that has a directory (the default).
    #[arg(long)]
    all: bool,
    /// Do not write; exit non-zero if any targeted adapter is missing or drifted.
    #[arg(long)]
    check: bool,
    /// Base directory containing the vendor dirs (defaults to the current dir).
    #[arg(long, default_value = ".")]
    base: PathBuf,
}

/// The engine-owned adapter content for a vendor — the single source of truth.
/// `render` (write) and `render --check` (compare) both call this, so they can
/// never disagree.
pub fn expected_adapter(vendor: &str) -> String {
    format!(
        "# Rusty IDD adapter — {vendor}\n\
         \n\
         GENERATED by `rusty-idd render {vendor}`. Do not hand-edit; \
         `rusty-idd render --check` (CI) fails on drift.\n\
         \n\
         `.{vendor}/` is a THIN ADAPTER (ADR-0010, ADR-0015). The workflow — \
         rules, gates, stage packages, the artifact DAG — lives in the Rusty IDD \
         engine, not here.\n\
         \n\
         Before any work:\n\
         1. Run `rusty-idd next` (human) or `rusty-idd next --json` (programmatic).\n\
         2. Do exactly what it reports; re-run to advance.\n\
         \n\
         Do not add always-loaded workflow prose to this directory.\n"
    )
}

pub(crate) fn lookup(name: &str) -> Option<(&'static str, &'static str)> {
    VENDORS.iter().copied().find(|(n, _)| *n == name)
}

/// `rusty-idd render` — write or check vendor adapters.
pub fn run(args: RenderArgs) -> i32 {
    let targets: Vec<(&str, &str)> = match &args.vendor {
        Some(v) => {
            match lookup(v) {
                Some(t) => vec![t],
                None => {
                    eprintln!("rusty-idd render: unknown vendor '{v}'; known: claude, codex, agents, devin");
                    return 2;
                }
            }
        }
        // default / --all: every known vendor that has a directory present.
        None => VENDORS
            .iter()
            .copied()
            .filter(|(_, dir)| args.base.join(dir).is_dir())
            .collect(),
    };

    if targets.is_empty() {
        println!(
            "rusty-idd render: no known vendor directories under {}",
            args.base.display()
        );
        return 0;
    }

    if args.check {
        run_check(&args, &targets)
    } else {
        run_write(&args, &targets)
    }
}

fn run_check(args: &RenderArgs, targets: &[(&str, &str)]) -> i32 {
    let mut drift: Vec<String> = Vec::new();
    for (name, dir) in targets {
        let path = args.base.join(dir).join(ADAPTER_FILE);
        let expected = expected_adapter(name);
        match std::fs::read_to_string(&path) {
            Ok(actual) if actual == expected => {}
            Ok(_) => drift.push(format!("drifted: {}", path.display())),
            Err(_) => drift.push(format!("missing: {}", path.display())),
        }
    }
    if drift.is_empty() {
        println!(
            "rusty-idd render --check: {} adapter(s) in sync",
            targets.len()
        );
        0
    } else {
        eprintln!(
            "rusty-idd render --check: {} adapter(s) out of sync:",
            drift.len()
        );
        for d in &drift {
            eprintln!("  {d}");
        }
        eprintln!("  fix: rusty-idd render --all");
        1
    }
}

fn run_write(args: &RenderArgs, targets: &[(&str, &str)]) -> i32 {
    for (name, dir) in targets {
        let vdir = args.base.join(dir);
        // An explicitly named vendor may create its dir; --all only fills dirs
        // that already exist (filtered above).
        if args.vendor.is_some() {
            if let Err(e) = std::fs::create_dir_all(&vdir) {
                eprintln!("rusty-idd render: failed to create {}: {e}", vdir.display());
                return 1;
            }
        }
        let path = vdir.join(ADAPTER_FILE);
        let expected = expected_adapter(name);
        // Idempotent: only write when content would change.
        if std::fs::read_to_string(&path).ok().as_deref() != Some(expected.as_str()) {
            if let Err(e) = std::fs::write(&path, &expected) {
                eprintln!("rusty-idd render: failed to write {}: {e}", path.display());
                return 1;
            }
        }
        println!("rendered: {}", path.display());
    }
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn expected_adapter_is_deterministic_and_points_at_next() {
        let a = expected_adapter("claude");
        let b = expected_adapter("claude");
        assert_eq!(a, b);
        assert!(a.contains("rusty-idd next"));
        assert!(a.contains("THIN ADAPTER"));
        assert!(a.contains(".claude/"));
    }

    #[test]
    fn lookup_knows_the_vendor_set() {
        assert_eq!(lookup("codex"), Some(("codex", ".codex")));
        assert_eq!(lookup("nope"), None);
    }
}
