//! `hf sync` (HFTASK-0011, ADR-0001 §6 / ADR-0003 rule 3) — two idempotent, one-way
//! maintenance passes, meant for session-end / post-merge:
//!
//!   Part A — registration ensure/repair: confirm this repo's membership in the meta
//!   workspace (`../.meta.yaml`) and de-duplicate its `../.gitignore` ignore line.
//!   Grep-guarded — never blind-append; there is no `meta project add`.
//!
//!   Part B — `.kb` mirror: write ledger-derived bodies INTO the planning plane,
//!   scoped to the generated slugs `context/overridable/{active,progress}` only.
//!   **ONE-WAY:** kb is never read back as execution truth; immutable/extensible/tasks
//!   slugs are never touched. Degrades (and says so) when `.kb`/`git-kb` is absent.
//!
//!   Part C — fleet rollup (HFTASK-0032, ADR-0004 §3.3 rev): roll each member repo's
//!   per-repo `.handoff/ledger.db` (the gitignored SOURCE of record) into the CENTRAL
//!   FLEET ledger at `<meta-root>/.handoff/ledger.db` via append-with-provenance
//!   re-chaining (CT/RFC6962 model) — each new source event (past the central
//!   `sync_cursor` for that repo) is re-appended onto the central tail with provenance
//!   (`origin_repo`/`origin_seq`/`origin_action_hash`), idempotent and crash-safe.
//!
//! `--dry-run` prints what Part B would write and what Part C WOULD roll up, without
//! creating/committing/appending anything.

use ledger::Ledger;
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::process::Command;
use work_order::PrioStr;
use work_order::{Status, WorkOrder};

const MIRROR_SLUGS: [(&str, &str); 2] = [
    ("context/overridable/active", "Active Context"),
    ("context/overridable/progress", "Progress"),
];
const GEN_TAG: &str =
    "<!-- generated by `hf sync` from ledger truth — do not hand-edit (ONE-WAY ledger→kb) -->";

#[derive(Debug, Clone, Serialize)]
struct SyncPhase {
    phase: &'static str,
    name: String,
    status: &'static str,
    message: String,
}

impl SyncPhase {
    fn ok(phase: &'static str, name: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            phase,
            name: name.into(),
            status: "ok",
            message: message.into(),
        }
    }
    fn skipped(phase: &'static str, name: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            phase,
            name: name.into(),
            status: "skipped",
            message: message.into(),
        }
    }
    fn blocked(phase: &'static str, name: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            phase,
            name: name.into(),
            status: "blocked",
            message: message.into(),
        }
    }
}

#[derive(Debug, Clone, Serialize)]
struct SyncReport {
    schema: &'static str,
    meta_root: String,
    dry_run: bool,
    phases: Vec<SyncPhase>,
}

pub fn cmd_sync(auto: bool, dry_run: bool, json: bool) {
    let _ = auto; // accepted for the hook contract (hf sync --auto); behavior is identical
    let Some(root) = crate::fleet::find_meta_root() else {
        eprintln!("hf sync: no .meta.yaml found from the current directory upward");
        std::process::exit(1);
    };
    let repo_name = std::env::current_dir()
        .ok()
        .and_then(|p| p.file_name().map(|s| s.to_string_lossy().into_owned()))
        .unwrap_or_default();

    let mut phases = Vec::new();
    phases.push(part_a_registration(&root, &repo_name, dry_run, !json));
    phases.push(part_b_kb_mirror(&root, &repo_name, dry_run, !json));
    phases.extend(part_c_rollup(&root, dry_run, !json));
    if json {
        let report = SyncReport {
            schema: "handoff.sync.v1",
            meta_root: root.to_string_lossy().into_owned(),
            dry_run,
            phases,
        };
        println!(
            "{}",
            serde_json::to_string_pretty(&report).unwrap_or_else(|_| "{}".into())
        );
    }
}

// --- Part C: fleet rollup (HFTASK-0032) -------------------------------------

/// Current wall-clock in nanoseconds (cursor `updated_ns` stamp; advisory only).
fn now_ns() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0)
}

/// Roll every member's per-repo `.handoff/ledger.db` into the central FLEET ledger.
///
/// CENTRAL = `<meta-root>/.handoff/ledger.db`. SOURCES = each member repo (from
/// `.meta.yaml`, including the handoff kernel repo itself) whose `.handoff/ledger.db`
/// exists and is NOT the central db. For each source: pull events past the central
/// `sync_cursor[member]` and roll them up in one transaction (idempotent + cursor-driven).
/// `--dry-run` only REPORTS the would-roll counts and appends NOTHING.
fn part_c_rollup(root: &Path, dry: bool, emit: bool) -> Vec<SyncPhase> {
    let mut phases = Vec::new();
    let central_path = root.join(".handoff").join("ledger.db");
    let central_canon = central_path.canonicalize().ok();

    let meta_yaml = std::fs::read_to_string(root.join(".meta.yaml")).unwrap_or_default();
    let members = crate::fleet::parse_members(&meta_yaml);
    if members.is_empty() {
        let msg = "no members in .meta.yaml — nothing to roll up";
        if emit {
            println!("hf sync [C] rollup: {msg}");
        }
        phases.push(SyncPhase::skipped("C", "rollup", msg));
        return phases;
    }

    // Open the central ledger ONCE for the whole pass (creates it if absent, unless dry).
    let central_lp = central_path.to_string_lossy().into_owned();
    let mut central = if dry {
        // In dry mode we only READ the central cursor; open read-only-ish (open() is fine,
        // it makes no events). If central doesn't exist yet, cursors are all None → all
        // source events would roll.
        Ledger::open(&central_lp).ok()
    } else {
        if let Some(parent) = central_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        match Ledger::open(&central_lp) {
            Ok(l) => Some(l),
            Err(e) => {
                let msg = format!("cannot open central FLEET ledger {central_lp}: {e}");
                eprintln!("hf sync [C] rollup: {msg}");
                phases.push(SyncPhase::blocked("C", "rollup", msg));
                return phases;
            }
        }
    };

    for member in &members {
        let src_path = root.join(member).join(".handoff").join("ledger.db");
        if !src_path.is_file() {
            continue; // git-text-only member / no local ledger — nothing to roll
        }
        // Never roll the central ledger into itself.
        if let (Ok(s), Some(c)) = (src_path.canonicalize(), central_canon.as_ref())
            && &s == c
        {
            continue;
        }

        let src_lp = src_path.to_string_lossy().into_owned();
        if ledger::file_is_legacy_sqlite(&src_lp) {
            let msg = format!(
                "legacy C-SQLite ledger detected at {src_lp}; rollup is blocked until migration. Plan: cd {} && cargo run -p hf --features legacy-sqlite -- migrate {src_lp}",
                root.join("handoff").display(),
            );
            eprintln!("hf sync [C] {member}: {msg}");
            phases.push(SyncPhase::blocked("C", member, msg));
            continue;
        }
        let src = match Ledger::open(&src_lp) {
            Ok(l) => l,
            Err(e) => {
                let msg = format!("cannot open source ledger: {e}");
                eprintln!("hf sync [C] {member}: {msg}");
                phases.push(SyncPhase::blocked("C", member, msg));
                continue;
            }
        };

        let cursor = central
            .as_ref()
            .and_then(|c| c.sync_cursor_get(member).ok().flatten())
            .unwrap_or(0);
        let rows = match src.events_after(cursor) {
            Ok(r) => r,
            Err(e) => {
                let msg = format!("cannot read events: {e}");
                eprintln!("hf sync [C] {member}: {msg}");
                phases.push(SyncPhase::blocked("C", member, msg));
                continue;
            }
        };

        if dry {
            let msg = format!(
                "would roll up {} event(s) (past cursor {cursor})",
                rows.len()
            );
            if emit {
                println!("hf sync [C] DRY {member}: {msg}");
            }
            phases.push(SyncPhase::ok("C", member, msg));
            continue;
        }

        let Some(central) = central.as_mut() else {
            continue;
        };
        match central.rollup_from(member, &rows, now_ns()) {
            Ok(stat) => {
                let msg = format!(
                    "appended {}, skipped {} (past cursor {cursor})",
                    stat.appended, stat.skipped_existing
                );
                if emit {
                    println!("hf sync [C] {member}: {msg}");
                }
                phases.push(SyncPhase::ok("C", member, msg));
            }
            Err(e) => {
                let msg = format!("rollup failed: {e}");
                eprintln!("hf sync [C] {member}: {msg}");
                phases.push(SyncPhase::blocked("C", member, msg));
            }
        }
    }
    phases
}

// --- Part A -----------------------------------------------------------------

/// True if `.gitignore` line, normalized, is this repo's ignore entry (`name`, `name/`,
/// `/name`, `/name/`).
fn is_repo_ignore(line: &str, repo: &str) -> bool {
    let t = line.trim();
    let t = t.trim_start_matches('/').trim_end_matches('/');
    t == repo
}

/// De-duplicate a repo's ignore line, keeping the first. Pure → testable. Returns the
/// (possibly unchanged) content and whether anything changed.
fn dedup_gitignore(content: &str, repo: &str) -> (String, bool) {
    let mut seen = false;
    let mut changed = false;
    let mut out = String::new();
    for line in content.lines() {
        if is_repo_ignore(line, repo) {
            if seen {
                changed = true;
                continue;
            }
            seen = true;
        }
        out.push_str(line);
        out.push('\n');
    }
    (out, changed)
}

fn part_a_registration(root: &Path, repo: &str, dry: bool, emit: bool) -> SyncPhase {
    let meta_yaml = std::fs::read_to_string(root.join(".meta.yaml")).unwrap_or_default();
    let needle = format!("  {repo}:");
    let registered = meta_yaml
        .lines()
        .any(|l| l.trim_end() == needle || l.starts_with(&needle));

    let gi_path = root.join(".gitignore");
    let gi = std::fs::read_to_string(&gi_path).unwrap_or_default();
    let present = gi.lines().any(|l| is_repo_ignore(l, repo));
    let (deduped, changed) = dedup_gitignore(&gi, repo);
    if changed && !dry {
        let _ = std::fs::write(&gi_path, &deduped);
    }

    let msg = format!(
        ".meta.yaml={} .gitignore={}{}",
        if registered {
            "registered"
        } else {
            "MISSING (add manually — no meta project add)"
        },
        if present { "ignored" } else { "MISSING" },
        match (changed, dry) {
            (true, true) => " (duplicate ignore line would be removed)",
            (true, false) => " (duplicate ignore line removed)",
            _ => "",
        }
    );
    if emit {
        println!("hf sync [A] {repo}: {msg}");
    }
    if registered && present {
        SyncPhase::ok("A", repo, msg)
    } else {
        SyncPhase::blocked("A", repo, msg)
    }
}

// --- Part B -----------------------------------------------------------------

fn run_git_kb(root: &Path, args: &[&str]) -> Result<String, String> {
    match Command::new("git-kb").args(args).current_dir(root).output() {
        Ok(o) if o.status.success() => Ok(String::from_utf8_lossy(&o.stdout).into_owned()),
        Ok(o) => Err(format!(
            "git-kb {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) => Err(format!("git-kb not runnable: {e}")),
    }
}

fn git_kb_available(root: &Path) -> bool {
    Command::new("git-kb")
        .arg("--version")
        .current_dir(root)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn status_of<'a>(card: &'a WorkOrder, replay: &'a [(String, Status)]) -> Status {
    replay
        .iter()
        .find(|(k, _)| k == &card.id)
        .map(|(_, s)| *s)
        .unwrap_or(card.status)
}

/// Ledger-derived "progress" body. Pure → testable.
fn progress_body(repo: &str, tasks: &[WorkOrder], replay: &[(String, Status)]) -> String {
    let done = tasks
        .iter()
        .filter(|t| status_of(t, replay) == Status::Done)
        .count();
    let mut s = format!(
        "{GEN_TAG}\n\n## Progress — {repo}\n\nDone: {done}/{}.\n\n### Open cards\n",
        tasks.len()
    );
    for t in tasks
        .iter()
        .filter(|t| status_of(t, replay) != Status::Done)
    {
        s.push_str(&format!(
            "- [{}] {} — {}\n",
            t.priority_str(),
            t.id,
            t.title
        ));
    }
    s
}

/// Ledger-derived "active" body. `next_desc` is the next-safe task (computed by the
/// caller via the kernel's dependency-aware `next_safe`, so the mirror matches
/// `hf resume`). Pure → testable.
fn active_body(repo: &str, next_desc: &str) -> String {
    format!("{GEN_TAG}\n\n## Active — {repo}\n\nNext: {next_desc}\nResume: `hf resume`\n")
}

/// Keep the existing frontmatter block (preserving the id), else synthesize a minimal
/// one. Pure → testable.
fn preserve_frontmatter(existing: &str, slug: &str, title: &str) -> String {
    let mut lines = existing.lines();
    if lines.next().map(str::trim) == Some("---") {
        let mut fm = String::from("---\n");
        for line in lines {
            fm.push_str(line);
            fm.push('\n');
            if line.trim() == "---" {
                return fm;
            }
        }
    }
    format!("---\nslug: {slug}\ntitle: \"{title}\"\ntype: context\nstatus: active\n---\n")
}

fn mirror_slug(root: &Path, slug: &str, title: &str, body: &str) -> Result<(), String> {
    if run_git_kb(root, &["show", slug]).is_err() {
        run_git_kb(
            root,
            &["create", "context", "--slug", slug, "--title", title],
        )?;
    }
    run_git_kb(root, &["checkout", slug])?;
    let ws = root.join(".kb/workspaces/main").join(format!("{slug}.md"));
    let cur = std::fs::read_to_string(&ws).unwrap_or_default();
    let fm = preserve_frontmatter(&cur, slug, title);
    std::fs::write(&ws, format!("{fm}\n{body}\n")).map_err(|e| e.to_string())?;
    run_git_kb(
        root,
        &[
            "commit",
            "-m",
            &format!("hf sync: mirror ledger truth → {slug}"),
        ],
    )?;
    Ok(())
}

fn git_porcelain(root: &Path, paths: &[&str]) -> Result<String, String> {
    let out = Command::new("git")
        .arg("-C")
        .arg(root)
        .arg("status")
        .arg("--porcelain")
        .arg("--")
        .args(paths)
        .output()
        .map_err(|e| format!("git status failed: {e}"))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        Err(format!(
            "git status failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

fn kb_store_dirty(root: &Path) -> Result<bool, String> {
    git_porcelain(root, &[".kb/store", ".kb/config.toml"]).map(|s| !s.trim().is_empty())
}

fn unique_sync_worktree(root: &Path) -> PathBuf {
    let mut p = std::env::temp_dir();
    let root_name = root
        .file_name()
        .map(|s| s.to_string_lossy())
        .unwrap_or_else(|| "meta".into());
    p.push(format!(
        "hf-kb-sync-{root_name}-{}-{}",
        std::process::id(),
        handoff_core::now_ns()
    ));
    p
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| format!("create {}: {e}", dst.display()))?;
    for ent in std::fs::read_dir(src).map_err(|e| format!("read {}: {e}", src.display()))? {
        let ent = ent.map_err(|e| format!("read entry in {}: {e}", src.display()))?;
        let ty = ent
            .file_type()
            .map_err(|e| format!("stat {}: {e}", ent.path().display()))?;
        let from = ent.path();
        let to = dst.join(ent.file_name());
        if ty.is_dir() {
            copy_dir_recursive(&from, &to)?;
        } else if ty.is_file() {
            if let Some(parent) = to.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| format!("create {}: {e}", parent.display()))?;
            }
            std::fs::copy(&from, &to)
                .map_err(|e| format!("copy {} -> {}: {e}", from.display(), to.display()))?;
        }
    }
    Ok(())
}

fn remove_git_worktree(root: &Path, worktree: &Path) {
    let _ = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["worktree", "remove", "--force"])
        .arg(worktree)
        .output();
    let _ = std::fs::remove_dir_all(worktree);
}

/// HFTASK-0092: mirror through a clean, disposable git worktree for the meta repo so an
/// unrelated dirty operator worktree cannot make `git-kb checkout` fail. Only `.kb/store`
/// is copied back, and only when the real KB store itself is clean; unrelated dirty files
/// are ignored, while KB-store conflicts fail as a typed phase blocker.
fn mirror_kb_isolated(
    root: &Path,
    bodies: &[(&str, &str, String)],
    dry: bool,
) -> Result<String, String> {
    if dry {
        return Ok(format!("would mirror {} slug(s)", bodies.len()));
    }
    if kb_store_dirty(root)? {
        return Err(
            "KB store has uncommitted changes; refusing to overwrite .kb/store (unrelated dirty files do not block sync)"
                .into(),
        );
    }
    let worktree = unique_sync_worktree(root);
    let status = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["worktree", "add", "--detach", "--quiet"])
        .arg(&worktree)
        .arg("HEAD")
        .status()
        .map_err(|e| format!("git worktree add failed: {e}"))?;
    if !status.success() {
        return Err(format!(
            "git worktree add failed with status {}",
            status.code().unwrap_or(-1)
        ));
    }
    let result = (|| {
        for (slug, title, body) in bodies {
            mirror_slug(&worktree, slug, title, body)?;
        }
        copy_dir_recursive(&worktree.join(".kb/store"), &root.join(".kb/store"))?;
        Ok::<_, String>(format!(
            "mirrored {} slug(s) via isolated worktree {}",
            bodies.len(),
            worktree.display()
        ))
    })();
    remove_git_worktree(root, &worktree);
    result
}

fn part_b_kb_mirror(root: &Path, repo: &str, dry: bool, emit: bool) -> SyncPhase {
    if !root.join(".kb").is_dir() || !git_kb_available(root) {
        let msg = "kb mirror skipped — no .kb or git-kb unavailable (degrade-and-say-so)";
        if emit {
            println!("hf sync [B] {msg}");
        }
        return SyncPhase::skipped("B", "kb_mirror", msg);
    }
    let tasks = crate::load_tasks();
    let replay = crate::current_statuses();
    let next_desc = crate::next_safe(&tasks, &replay)
        .map(|t| format!("{} — {}", t.id, t.title))
        .unwrap_or_else(|| "(no open cards)".into());
    let bodies = [
        (
            MIRROR_SLUGS[0].0,
            MIRROR_SLUGS[0].1,
            active_body(repo, &next_desc),
        ),
        (
            MIRROR_SLUGS[1].0,
            MIRROR_SLUGS[1].1,
            progress_body(repo, &tasks, &replay),
        ),
    ];
    if dry && emit {
        for (slug, _, body) in &bodies {
            println!("hf sync [B] DRY would mirror {slug}:\n{body}");
        }
    }
    match mirror_kb_isolated(root, &bodies, dry) {
        Ok(msg) => {
            if emit && !dry {
                println!("hf sync [B] {msg} (one-way ledger→kb)");
            }
            SyncPhase::ok("B", "kb_mirror", msg)
        }
        Err(e) => {
            eprintln!("hf sync [B] kb mirror blocked: {e}");
            SyncPhase::blocked("B", "kb_mirror", e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dedup_keeps_first_ignore_line() {
        let gi = "node_modules/\nhandoff/\nfoo\nhandoff/\n";
        let (out, changed) = dedup_gitignore(gi, "handoff");
        assert!(changed);
        assert_eq!(out.matches("handoff/").count(), 1);
        assert!(out.contains("node_modules/"));
    }

    #[test]
    fn dedup_noop_when_single() {
        let gi = "handoff/\nfoo\n";
        let (_, changed) = dedup_gitignore(gi, "handoff");
        assert!(!changed);
    }

    #[test]
    fn frontmatter_preserved_with_id() {
        let existing = "---\nid: 019e-abc\nslug: context/overridable/active\ntitle: \"Active Context\"\n---\nold body\n";
        let fm = preserve_frontmatter(existing, "context/overridable/active", "Active Context");
        assert!(fm.contains("id: 019e-abc"));
        assert!(fm.trim_end().ends_with("---"));
        assert!(!fm.contains("old body"));
    }

    #[test]
    fn frontmatter_synthesized_when_absent() {
        let fm = preserve_frontmatter(
            "no frontmatter here",
            "context/overridable/progress",
            "Progress",
        );
        assert!(fm.contains("slug: context/overridable/progress"));
    }

    #[test]
    fn bodies_carry_generated_tag_and_are_one_way() {
        let p = progress_body("handoff", &[], &[]);
        let a = active_body("handoff", "HFTASK-0011 — hf sync");
        assert!(p.contains("generated by `hf sync`"));
        assert!(a.contains("generated by `hf sync`"));
        assert!(a.contains("HFTASK-0011 — hf sync"));
        assert!(p.contains("Done: 0/0"));
    }

    /// HFTASK-0092: unrelated dirty files in the ambient meta worktree must not block the
    /// isolated KB writer. Only dirty KB store files are a legitimate clobber risk.
    #[test]
    fn kb_store_dirty_ignores_unrelated_dirty_worktree_files() {
        let root = temp_meta_root(&[]);
        std::process::Command::new("git")
            .args(["init", "-q"])
            .current_dir(&root)
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.email", "t@example.com"])
            .current_dir(&root)
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["config", "user.name", "t"])
            .current_dir(&root)
            .output()
            .unwrap();
        std::fs::create_dir_all(root.join(".kb/store")).unwrap();
        std::fs::write(root.join(".kb/store/manifest.json"), "{}\n").unwrap();
        std::process::Command::new("git")
            .args(["add", ".kb/store/manifest.json"])
            .current_dir(&root)
            .output()
            .unwrap();
        std::process::Command::new("git")
            .args(["commit", "-m", "seed kb store"])
            .current_dir(&root)
            .output()
            .unwrap();
        std::fs::write(root.join("unrelated.txt"), "dirty but not kb\n").unwrap();
        assert!(
            !kb_store_dirty(&root).unwrap(),
            "unrelated ambient worktree dirt must not block KB mirror isolation"
        );

        std::fs::write(root.join(".kb/store/manifest.json"), "{\"dirty\":true}\n").unwrap();
        assert!(
            kb_store_dirty(&root).unwrap(),
            "dirty .kb/store is blocked to avoid clobbering KB changes"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn sync_phase_serializes_a_b_c_statuses() {
        let phases = vec![
            SyncPhase::ok("A", "registration", "ok"),
            SyncPhase::blocked("B", "kb_mirror", "dirty kb store"),
            SyncPhase::ok("C", "memberx", "appended 1"),
        ];
        let report = SyncReport {
            schema: "handoff.sync.v1",
            meta_root: "/tmp/meta".into(),
            dry_run: false,
            phases,
        };
        let json = serde_json::to_value(report).unwrap();
        assert_eq!(json["schema"], "handoff.sync.v1");
        assert_eq!(json["phases"][0]["phase"], "A");
        assert_eq!(json["phases"][1]["phase"], "B");
        assert_eq!(json["phases"][1]["status"], "blocked");
        assert_eq!(json["phases"][2]["phase"], "C");
    }

    // ----- HFTASK-0032: Part C rollup wiring (isolated temp meta-roots) -----

    /// Build an isolated temp meta-root with a `.meta.yaml` listing `members`. NEVER the
    /// real workspace. Returns the root dir.
    fn temp_meta_root(members: &[&str]) -> std::path::PathBuf {
        let mut root = std::env::temp_dir();
        root.push(format!(
            "hf-sync-test-{}-{:?}-{}",
            std::process::id(),
            std::thread::current().id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&root).unwrap();
        let mut yaml = String::from("projects:\n");
        for m in members {
            yaml.push_str(&format!("  {m}:\n    repo: git@example/{m}.git\n"));
        }
        std::fs::write(root.join(".meta.yaml"), yaml).unwrap();
        std::fs::create_dir_all(root.join(".handoff")).unwrap();
        root
    }

    /// Seed a member repo's per-repo source ledger with `n` witnessed events.
    fn seed_member_ledger(root: &Path, member: &str, n: usize, start_ts: u64) {
        let dir = root.join(member).join(".handoff");
        std::fs::create_dir_all(&dir).unwrap();
        let lp = dir.join("ledger.db").to_string_lossy().into_owned();
        let mut led = Ledger::open(&lp).unwrap();
        for i in 0..n {
            led.append(
                "checkpoint",
                &format!("{member}-WO"),
                "{}",
                start_ts + i as u64,
            )
            .unwrap();
        }
    }

    fn central_count(root: &Path) -> usize {
        let lp = root
            .join(".handoff")
            .join("ledger.db")
            .to_string_lossy()
            .into_owned();
        Ledger::open(&lp)
            .and_then(|l| l.all_events())
            .map(|e| e.len())
            .unwrap_or(0)
    }

    /// AC5: `--dry-run` reports would-roll counts and writes NOTHING to central.
    #[test]
    fn part_c_dry_run_writes_nothing() {
        let root = temp_meta_root(&["repo_a", "repo_b"]);
        seed_member_ledger(&root, "repo_a", 3, 100);
        seed_member_ledger(&root, "repo_b", 2, 200);

        part_c_rollup(&root, true, true); // dry
        // Central ledger.db should not even be created by a dry pass (no append path).
        assert!(
            !root.join(".handoff").join("ledger.db").is_file() || central_count(&root) == 0,
            "dry-run must not append to central"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    /// AC1+AC2+AC3: real rollup → idempotent re-run → incremental.
    #[test]
    fn part_c_rollup_idempotent_and_incremental() {
        let root = temp_meta_root(&["repo_a", "repo_b"]);
        seed_member_ledger(&root, "repo_a", 3, 100);
        seed_member_ledger(&root, "repo_b", 2, 200);

        // First sync: 3 + 2 = 5 rolled into central, verified.
        part_c_rollup(&root, false, true);
        assert_eq!(central_count(&root), 5, "first rollup lands all 5");
        let lp = root
            .join(".handoff")
            .join("ledger.db")
            .to_string_lossy()
            .into_owned();
        assert_eq!(
            Ledger::open(&lp).unwrap().verify_witness_chain().unwrap(),
            5
        );

        // AC2 idempotent: re-run rolls up nothing new.
        part_c_rollup(&root, false, true);
        assert_eq!(central_count(&root), 5, "re-run is idempotent (0 new)");

        // AC3 incremental: add 2 to repo_a, re-sync → exactly 2 more.
        seed_member_ledger(&root, "repo_a", 2, 300); // appends onto repo_a's existing ledger
        part_c_rollup(&root, false, true);
        assert_eq!(
            central_count(&root),
            7,
            "incremental rolls exactly the 2 new"
        );
        assert_eq!(
            Ledger::open(&lp).unwrap().verify_witness_chain().unwrap(),
            7
        );

        let _ = std::fs::remove_dir_all(&root);
    }

    /// The central ledger is never rolled into itself even though `handoff` (the kernel
    /// repo) IS a valid source: a member whose ledger path canonicalizes to central is
    /// skipped. Here we simulate by NOT giving central a self-referential member; instead
    /// assert a member with no ledger is silently skipped (git-text-only).
    #[test]
    fn part_c_skips_members_without_ledger() {
        let root = temp_meta_root(&["repo_a", "git_text_only"]);
        seed_member_ledger(&root, "repo_a", 2, 100);
        // git_text_only has a .handoff dir but NO ledger.db
        std::fs::create_dir_all(root.join("git_text_only").join(".handoff")).unwrap();

        part_c_rollup(&root, false, true);
        assert_eq!(
            central_count(&root),
            2,
            "only repo_a rolled; text-only skipped"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    /// HFTASK-0091: a legacy C-SQLite source ledger is an explicit rollup blocker. The
    /// default no-C sync path must not open it as redb and must not advance central state
    /// as if the member were empty.
    #[test]
    fn part_c_legacy_sqlite_source_is_blocked_not_treated_empty() {
        let root = temp_meta_root(&["legacy_member"]);
        let dir = root.join("legacy_member/.handoff");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("ledger.db"), b"SQLite format 3\0legacy fixture").unwrap();

        part_c_rollup(&root, false, true);

        assert_eq!(
            central_count(&root),
            0,
            "legacy SQLite members are blocked pending migration, never rolled as empty"
        );
        let _ = std::fs::remove_dir_all(&root);
    }
}
